# Generated by Django 4.1.7 on 2023-03-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date_of_foundation', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, default='default_logo.jpg', null=True, upload_to='')),
                ('bio', models.TextField(blank=True, null=True)),
                ('country', models.CharField(db_index=True, max_length=70)),
                ('stadium', models.CharField(blank=True, max_length=200, null=True)),
                ('titles', models.TextField(blank=True, null=True)),
                ('players_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
