# Generated by Django 4.1.7 on 2023-03-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ['name']},
        ),
    ]
