# Generated by Django 4.1.7 on 2023-03-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_rename_teams_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('tournament', models.CharField(blank=True, max_length=200, null=True)),
                ('referee', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('team_away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_away', to='teams.team')),
                ('team_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_home', to='teams.team')),
            ],
        ),
    ]
