# Generated by Django 4.1.7 on 2023-03-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
    ]
